### ISSUE TITLE
Dataset licence

### ISSUE THREAD

**Issue by idevisser** [SEMICeu/DCAT-AP#108]
In ISO 19115 metadata / the netherlands, the licence  refers to a dataset, not to it's distribution. Please add a relation to licence from dcat:DAtaset

**Comment by bertvannuffelen** [comment]
This request is more a request for the w3c DCAT 2.0 working group, as DCAT-AP should be ideally a pure restriction on DCAT for Open Data.

But as it turns out DCAT 2.0 has attached this property to dcat:Resource, making hence dct:license also available at the dataset level. However as pointed out in issue #66 one should take into account the recommendation that the license should be best specified at the most granular level and that these value should not in conflict with the values at the dataset level. 

For that reason dct:license is recommended for dcat:Distribution in DCAT-AP 1.2 and this approach has been taken over for DCAT-AP 2.0. For that reason dct:license is not present at the dataset level in DCAT-AP.

Note that for transforming a catalog in ISO 19115 to DCAT-AP 2.0 this is can be fully automated by a script, resulting in the same semantics at DCAT-AP 2.0 level as provided by the source catalog in ISO.
The other way around DCAT-2.0 -> ISO 19115 cannot be automated, because there might be different license used for 2 distributions for a dataset and a machine cannot make a choice here. That is a human's job.

**Comment by bertvannuffelen** [comment]
resolution: feedback provided which addresses the request.

**Comment by andrea-perego** [comment]
Just to note that the mapping from ISO 19115 / INSPIRE metadata to DCAT-AP is actually what GeoDCAT-AP has been designed for.

This issue is addressed in GeoDCAT-AP by associating with the distribution(s) the licence specified in  ISO 19115 / INSPIRE at the dataset level - see [§B.15 of the GeoDCAT-AP specification](https://semiceu.github.io/GeoDCAT-AP/drafts/latest/#conditions-for-access-and-use-and-limitations-on-public-access-use-limitation-and-access-other-constraints).

Of course, this approach can be revised, if need be, in a new release of GeoDCAT-AP - taking however into account compliance with DCAT-AP.
