### ISSUE TITLE
update OWL for DCAT-AP 2.0

### ISSUE THREAD

**Issue by Giorgia77** [SEMICeu/DCAT-AP#138]
We tried to convert DCAT-AP 2.0 rdf into OWL format, through OWL API (http://mowl-power.cs.man.ac.uk:8080/converter/), but the result is not satisfactory and it does not open in Protégé. Is there anybody able to provide me with an update DCAT-AP ontology ( the one I found in the old related thread it shows inconsistencies with the new version)? 
Thank you

**Comment by EmidioStani** [comment]
In addition, as DCAT-AP is based on DCAT it would be sufficient either to import in Protege the entire DCAT ontology or each single concept which is described already as owl:Class or owl:ObjectProperty (see: https://www.w3.org/ns/dcat.ttl).

This issue is related to the closed #52

**Comment by bertvannuffelen** [comment]
DCAT-AP is an application profile of DCAT. So as @EmidioStani  wrote you combine the existing resources of all vocabularies on which DCAT-AP is based, and then this should become an consistent graph.   

I am however not aware of a maintained aggregated version and if this results in a structure which an OWL editor like Protégé would like. If you discover issues during this process you are welcome to post them here, but it might be that the issue can only resolved by addressing it at the imported vocabularies.

Also if you could automate this aggregation process and share that would be great. It would ease the maintenance of changes throughout a distributed network of resources.  Because as now, the process we are discussing is a manual process and that makes is very hard to discuss issues or any improvements.
