### ISSUE TITLE
Cardinality of dct:type in DCAT-AP (PDF) specification

### ISSUE THREAD

**Issue by aidig** [SEMICeu/DCAT-AP#153]
I noted the mismatch in the cardinality of the DCAP-AP specification and the SHACL constraints in version 2.0.0 in this (closed) [issue](https://github.com/SEMICeu/DCAT-AP/issues/126#issuecomment-621023388), stating that the SHACL implementation would reflect the DCAT correctly and that the PDF specification should be amended. 

Instead the SHACL file in version 2.0.1 has been changed and now restricts the use of dct:type to a maximum multiplicity of 1 although DCAT clearly states that "_It is also possible for multiple classifications to be present in a single description_". 

Please see section 5.5 Classifying dataset types in DCAT 2.0:
https://www.w3.org/TR/vocab-dcat-2/#classifying-dataset-types

Hence the cardinality should not be 0..1 for this property.

What are the arguments for changing the SHACL contraints and not the PDF specification here?
https://github.com/SEMICeu/DCAT-AP/issues/126

**Comment by bertvannuffelen** [comment]
@aidig the restriction has been already in DCAT-AP 1.2.1. So it is an additional restriction of DCAT in the context of DCAT-AP. 
With the closed issue we addressed the incoherence between the human readible and machine readible specifications.

Your comment
> 
> Hence the cardinality should not be 0..1 for this property.
> 
contains an underlying question for me: can DCAT-AP put additional constraints on DCAT? 
For me, this is the purpose of DCAT-AP: namely to add constraints to DCAT so that it is better fitted for the Open Data Portal community in Europe.  

Then to the motivation of the restriction itself: I think the original objective was to capture only one aspect of categorisation of datasets, and that this categorisation is determined by the concepts in one conceptscheme. If I remember right, the Publications Office requested this ability in the context of the EU ODP. According to the DCAT-AP specification there is no concept-scheme being created yet, but when exploring the PO NAL list I find this: https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/dataset-type. 

Questions are thus:

- do we maintain the restriction to be max 1 value for dct:type?
- do we include the above list as (recommended/mandatory) codelist?

**Comment by aidig** [comment]
Indeed DCAT-AP should definately be able to put additional contraints on DCAT in the context of this specific application _for data portals in Europe_ in general (and not limited to EU ODP). So, in other words, while there could be benefits for the data portals in Europe using the same concept scheme to classify datasets, what are the benefits of _not permitting_ datasets to be classified separately using values from different vocabularies as well?

**Comment by bertvannuffelen** [comment]
wg 21 Oct 2021 decided to 
   lift the max-cardinality constraint to allow multiple values
   add the https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/dataset-type as recommended controlled vocabulary.
