### ISSUE TITLE
Next Major Release - Change And Release Management

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#189]
Hello,

when [DCAT-AP 2.0](https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe/news/dcat-ap-major-release) was released, it was said, 
> (...) certain items have not been tackled. These topics will be taken into consideration in the next releases of DCAT-AP, in line with the Change and Release Management Policy for DCAT-AP.

The link to the "Change and Release Management Policy for DCAT-AP" does not work anymore, but I assume it is [this](https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/solution/dcat-application-profile-data-portals-europe/document/change-and-release-management-policy-dcat-ap).

If the policy wasn't changed but carried forward for 2020/2021, the deadline for new change requests would end **this month**:

![grafik](https://user-images.githubusercontent.com/14979304/110627222-faa88d00-81a1-11eb-9a89-013bf454a496.png)

Is this the plan? If not, what is the plan?

**Comment by init-dcat-ap-de** [comment]
Hello,

we are looking forward to the upcoming webinar ( https://joinup.ec.europa.eu/collection/semantic-interoperability-community-semic/event/dcat-ap-webinar-15th-september-1000-cet ).

Would it be possible to tag the issues we are going to discuss? Otherwise "Agree on the resolution of some of the issues" will be hard to archive.
Depending on the issues and the proposed resolutions we might have to reach out to our data providers.

**Comment by bertvannuffelen** [comment]
The objective is to create a new release which would include many of the issues. However, due to time constraints, the webinar will be focussing on some conceptual topics, in order to provide possible resolutions for a number of issues. Topics which have a concrete request and proposal can be adopted if the community accepts the proposed resolution.

The structuring and alignment of the issues is as follows:

- status:wont-fix: issues that will be closed after this iteration. Mostly questions, announcements, open discussions
- status:fixed : issues that have a resolution that is already applied in the draft release. Mostly editorial issues
- status:waitingForDecisionW3C: issues that cannot be resolved without an statement at the level of W3C. DCAT-AP contributors are requested to discuss these at the level of W3C


Community feedback is requested for the following labels:
- status:resolution-provided : issues that have a clear resolution statement, which has not yet been applied in the draft-release. DCAT-AP contributors are requested to confirm the resolution. If no negative feedback comes, then this resolution will be implemented in the next release
- feedback-requested: issues with concrete questions for which the community has to provide an opinion. Unless there is consensus these will NOT be adopted in the next release
- topic:cataloged_resource: issues that are related to the conceptual discussion on the nature of a dataset/data service/distribution.

Issues that are for now out of scope are labeled with future-work.

I hope this will allow you to get a grip on the issue list.

**Comment by bertvannuffelen** [comment]
In the webinar of 16 jan 2024 an improved handling of the issues, followup of the issues and creation of new releases has been presented. As this approach is more generally applicable than only for DCAT-AP, for instance also for the Core Vocabularies. The general guidelines are expressed here: https://github.com/SEMICeu/Policies-Governance-Maintenance-Communication.

As ongoing work: we will include references in the relevant places and further elaborate these.
