### ISSUE TITLE
Move added properties from Dataset to Ressource

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#194]
A similar request as https://github.com/w3c/dxwg/issues/1253 or https://github.com/SEMICeu/DCAT-AP/issues/190:

Is it planned to move `foaf:page`, `adms:sample`, `adms:versionNotes` or `owl:versionInfo` to dcat:Resource (or add them explicitly to dcat:DataService)?

foaf:page is probably unneccessary, since the dcat:DataService has dcat:endpointDescription. But adding a sample distribution of the expected data of a DataService, a version number and a change log could be very valuable.

**Comment by bertvannuffelen** [comment]
This topic I propose to take into a larger perspective on the relationship with DCAT and the organisation of the application profile. A lot dependents on the notion of _reuse_ and how to formulate that in an application profile.


The notion of [Cataloged Resource](https://w3c.github.io/dxwg/dcat/#Class:Resource) is an abstract entity which has as purpose to provide a set of properties that might be used to describe cataloged resources. It does not mean that if a property <p> is mentioned in Cataloged Resource that every subclass must have it. DCAT only enforces that we cannot introduce  in a profile a new property <q> for a subclass of Cataloged Resource having the exact same semantics as <p>.  (Actually more precisely it is bad practice, as prohibition cannot be checked.)

With the cataloged resource we have now 2 reuse methodes in DCAT: 
- via the subclassing of cataloged resource
- via direct inclusion as a property on a subclass 

The first has a challenge: how do we express differences in use for a subclass. Suppose we want to express that the codelist for publisher of datasets is list A and the codelist for dataservices list B. We would expect that this information is expressed at the level of the subclass.
The second has a challenge that one cannot immediately see if a property <p> available in subclass A and B are used in the same way. 
A mix is also annoying: because it causes to switch between the two perspectives.

And then there is the absence of the property. What does that mean? For instance, today the property dct:identifier associated in DCAT with Cataloged Resource is not mentioned in DCAT-AP for a data service. Do we mean then that a DCAT-AP data service should not have a value for dct:identifier. Or that there has been no expression about the usage of that property in DCAT-AP? 

So it would be good to express interpretation rules on how the application profile should be read. With the subclassing this has become more important.

**Comment by bertvannuffelen** [comment]
in webinar https://github.com/SEMICeu/DCAT-AP/tree/master/Webinars/15-Sept-2021 it has been decided to not exploit catalogued resources as an abstract notion to aid the editorial management of the entities.

Instead of that, only the business relevant classes are maintained.
