### ISSUE TITLE
Range of dct:type in dcat:Dataset

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#205]
DCAT-AP has as range `skos:Concept`.
DCAT has as range `rdfs:Class`: https://www.w3.org/TR/vocab-dcat-2/#Property:resource_type

Should we hormonize with DCAT? DCAT 2 has added the property, while DCAT-AP had it earlier.

**Comment by bertvannuffelen** [comment]
Actually this is not inconsistent. 

Technically speaking skos:Concept is a rdfs:Class. [1] So DCAT-AP is more specific then DCAT. So technically it is all fine. 

But even from an intentional perspective this is not very limiting. Anything could be declared a skos:Concept. The only incentive we obtain here is that implementors will consider to use values that are part of a properly managed controlled vocabulary. This formulation highlights that intention, but it does not block the usage of ad-hoc values.   

[1] See https://www.w3.org/2009/08/skos-reference/skos.rdf

**Comment by init-dcat-ap-de** [comment]
Yes, it's not a problem, more a reminder. At the last webinar we discussed, that we will check the usefulnes and consistancy of every attribute. Here we are more specific than DCAT and we should decide whether it is, because there is a need and a use case to be more specific or whether it is just a coincidence.
