### ISSUE TITLE
SHACL: GeoNamesRestriction-Shape Is Not Fulfilled By Using GeoNames-URIs

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#218]
The GeoNamesRestriction-shape is not fulfilled by using geonames-uris:

```:GeoNamesRestriction
    a sh:NodeShape ;
    rdfs:comment "Geo names restriction" ;
    rdfs:label "Geo names restriction" ;
    sh:property [
        sh:hasValue <http://sws.geonames.org> ;
        sh:minCount 1 ;
        sh:nodeKind sh:IRI ;
        sh:path skos:inScheme
    ] 
```

If I use e.g. `<https://sws.geonames.org/2921044/>`, the RDF does not include an inScheme path.

Possible solution: only test that the IRI starts with "https://sws.geonames.org/"
(Could be applicable to the IANA-lists as well)

**Comment by bertvannuffelen** [comment]
I understand the approach. I am personally reluctant to base validation on string processing, but I agree that the current rule is not much of a validation rule.

**Comment by bertvannuffelen** [comment]
I did additional checks on data.europa.eu and I discovered the use of
  - http://sws.geonames.org (HTTP instead of HTTPS)
  - http://www.geonames.org (website instead of IRI)
  - https://www.geonames.org (website instead of IRI)

On the first, maybe in the past HTTP was published, but today it is only HTTPS.
On the second, the usual challenge to ensure that the right identifiers are used instead of the browser URLs.

I also looked at the geonames ontology, which indeed does not defines the geonames instances as skos:Concepts. And it is hard to do a full download of all URIs before validation.

So maybe for these cases a "textual" test could be appropriate.

**Comment by bertvannuffelen** [comment]
In the mdr-vocabularies.shape.ttl now a test on the prefix of the URIs has been added.

```
:GeoNamesRestrictionRegexURI
    rdfs:comment "Geonames restriction - base itself on URI structure" ;
    rdfs:label "Geonames restriction" ;
    a sh:NodeShape ;
    sh:pattern "^https://sws.geonames.org" .
```
