### ISSUE TITLE
dcat:resource in DCAT 3.0

### ISSUE THREAD

**Issue by bertvannuffelen** [SEMICeu/DCAT-AP#243]
**case:**
dcat:resource has been introduced as the superproperty of dcat:service and dcat:dataset.

**impact assessment**

1. The property  could be used to encode the requirement that a catalogue should be non-empty. ​The SHACL templates must import the subclass relationship in order to guarantee correct validation​.
2. It is unclear how to indicate the dataset series that are in the catalogue. There exists no specific subproperty in DCAT 3.0, while specific properties dcat:dataset, dcat:dataservice, dcat:catalog do exist.​
This is connected with issue #163 on how to support profiling of DCAT, as it should be clear what are the constraints to hold for the entities in the catalogue.

**Comment by init-dcat-ap-de** [comment]
Regarding 1.: We don't see the need to enforce that a catalog is not empty. We would prefer if this (previously existing) rule would not come back.

Regarding 2.: Since `dcat:DatasetSeries` is  a sub-class of `dcat:Dataset`, we assume that `dcat:dataset` should be used. Since DCAT-AP does not shows `dcat:Resource`, we don't see the need show `dcat:resource`. There is in our opinion no use-case in this AP, where we need to add arbitrary resources.

**Comment by andrea-perego** [comment]
@init-dcat-ap-de said:

> Regarding 2.: Since `dcat:DatasetSeries` is a sub-class of `dcat:Dataset`, we assume that `dcat:dataset` should be used. 

Indeed. This is also shown in [Example 37](https://www.w3.org/TR/vocab-dcat-3/#ex-dataset-series-containment) of DCAT3.

If you think that DCAT3 should be more explicit on how to link a `dcat:Catalog` to a `dcat:DatasetSeries`, I recommend raising an issue in https://github.com/w3c/dxwg/issues
