### ISSUE TITLE
Checksum in DCAT 3.0

### ISSUE THREAD

**Issue by bertvannuffelen** [SEMICeu/DCAT-AP#244]
Checksum has been adopted from DCAT-AP.  

So far there are no differences detected. The proposal is to adopt the proposed definitions by DCAT 3.0. 
This should lead to only minor adaptations to DCAT-AP.

**Comment by init-dcat-ap-de** [comment]
**Bug:** The link in the [Controlled vocabularies to be used](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#controlled-vocabularies-to-be-used) is https://spdx.org/rdf/terms/#d4e1968 instead of https://spdx.org/rdf/terms/#d4e2129
(My guess is that they recreate the urls when they build the documentation, even though cool URIs don't change...)

**Feature Request:** The Usage note of the [attribute `checksum`](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Checksum.algorithm) should direct people to the [Controlled vocabularies to be used](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#controlled-vocabularies-to-be-used).
The supportive entity [Checksum Algorithm](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#ChecksumAlgorithm) seems unnecessary, even confusing, considering that you should use a NAL.
![grafik](https://github.com/SEMICeu/DCAT-AP/assets/14979304/f9df431d-a603-4395-bd60-ba58b04c6b13)

(This is true for other attributes using a NAL as well.)

**Comment by bertvannuffelen** [comment]
@init-dcat-ap-de, when investigating this case I find there are inconsistencies on the SPDX side.

The property spdx:algorithm is stated in the documentation with IRI <http://spdx.org/rdf/terms#algorithm> while the html local reference is <https://spdx.org/rdf/terms/#d4e46>. Thus it is unclear which one it to be used. The explicit named one or the opaque one. Given that the html documentation states an explicit IRI I propose to take these ones as normative and use <http://spdx.org/rdf/terms#algorithm>. 

![image](https://github.com/SEMICeu/DCAT-AP/assets/1999213/348d3862-3814-489a-90ea-acd11c6259dc)


Secondly the range of this propertu is defined by SPDX. That has been taken over in the DCAT-AP specification. In SPDX they define a codelist as instances of the spdx:ChecksumAlgorithm class.

![image](https://github.com/SEMICeu/DCAT-AP/assets/1999213/56183f7d-30f9-467d-bf08-6ea913058f1a)

This is the reason why the link to the codelist is pointing to this location. 

In essence from the moment you use the property [checksum]([checksum](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Distribution.checksum))  for a Distribution, the rules of the spdx ontology apply.
Similar as my response to the use of NALs for spatial (#266) , this is another case where codelists are encoded in a different way as commonly recommended to rely on SKOS. However this instance list still matches most of the [requirements for controlled vocabularies](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#requirements-for-controlled-vocabularies).

Note that for this algorithm codelist there is no "official name" given by SPDX. The instances are just managed as part of SPDX in general. So to refer to the list we use reference to a html achor in the SPDX specification, which happens to look like a persistent URI.

**Comment by bertvannuffelen** [comment]
Ensured that the reference to the instances is still correct. Further no change has happened.
