### ISSUE TITLE
Range of locn:geometry is locn:Geometry

### ISSUE THREAD

**Issue by bertvannuffelen** [SEMICeu/DCAT-AP#247]
**Observation​**

- In DCAT 2.0: rdfs:Literal​
- DCAT 3.0: aligned with Core Location 2.0 (locn)​

**Proposal​**
To align with DCAT 3.0​

**Impact​**
Backward incompatibility with DCAT 2.0 (Literal -> Class)

**Comment by bertvannuffelen** [comment]
This is reopening issue #177

**Comment by init-dcat-ap-de** [comment]
We support the alignment.

Technically you are right about the backward incompatibility, but this problem is already adressed by the [locn ontology](https://www.w3.org/ns/locn#locn:Geometry):
![grafik](https://user-images.githubusercontent.com/14979304/203947742-242a5599-3c81-4a74-806e-80b5412142b0.png)

The usage notes of https://www.w3.org/ns/locn#locn:geometry allow nearly *everything* as range:

![grafik](https://user-images.githubusercontent.com/14979304/203947690-f451f388-1ca0-48fa-9f6b-f00c5b9b4e08.png)

I think we should use this flexibillity and recommend a `locn:geometry` representation that can be proccessed by the EDP for visualization.

**Comment by bertvannuffelen** [comment]
The semantical alignment is addressed.  For processing capabilities by EDP, it might be a topic for the upcomming geoDCAT-AP aligment.
