### ISSUE TITLE
dcat:DataSeries: Controlled Vocabulary For dcterms:type

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#249]
As discussed in the last webinar and here (https://github.com/SEMICeu/DCAT-AP/issues/240#issuecomment-1327166342) this issue is to discuss the needed entries for a controlled vocabulary that could be used with dct:type, similar to [dataset types](https://op.europa.eu/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/dataset-type).

To me are currently the following values known:

- spatial
- temporal
- topic

**Comment by jakubklimek** [comment]
I suggest that we accompany each type with an example, to avoid cases where each reader interprets e.g. "temporal series" differently, and to make sure that everyone sees their series in the list.
We could take this opportunity to specify the series types a bit further.
E.g.

**Temporal series with no overlap** comprises datasets:
Budget 2020, Budget 2021, Budgets 2022 where e.g. no part of Budget 2020 is part of Budget 2021

**Temporal series with overlap** - this can be also viewed as **versions series**, or **snapshots** - where we have:
Blacklist of companies not paying their taxes in March, April, May - some companies may be on the list in various months, some not, and comparison between versions may be meaningful, e.g. to say for how long a company was on the blacklist

Then there is the question of what happens if we combine spatial and temporal series, e.g., **budgets of cities in time**. Is there a preference, recommendation or is it up to the publishers?

1. Flat spatial-temporal series with datasets with various spatial and temporal coverages (this could be an additional type)
2. Spatial series of individual temporal series
3. Temporal series of individual spatial series

Regarding the **topic series**, my examples would be, for the "budget" topic:

1. "Budget of a company" dataset (distributed as XML and CSV, i.e. 2 distributions)
2. N datasets with "codelists used in budget of a company", distributed as SKOS concept schemes in RDF
3. "Budget and codelists" dataset distributed as a data service, e.g. SPARQL endpoint

Another example could be the topic "financial datasets", grouping in a series:

1. Budget dataset
2. Spending dataset
3. Budget outlook dataset

I am stating the examples rather to spark discussion (possibly identify distinct issues), rather than saying I am convinced they are the correct usage of DatasetSeries.

**Comment by ODP-hil** [comment]
Thanks for your comment @init-dcat-ap-de. Indeed the rdfs:type already denotes the "general" classification and a "general" dct:type would be redundant. However, I agree that providing an explanation of why certain datasets are grouped in a series is useful.

In my understanding we should then consider:
1. If this could be done by adding Concepts to the [dataset-type](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/dataset-type) List (@MPaunescu), and
2. which types of dataset-series to include (for me spatial, temporal and thematic should cover most cases). 

I am pasting a more relaxed definition of the sub-types, to allow inclusion of less structured series:

- **Temporal dataset-series** - A series of datasets that describe similar content of distinct temporal coverage. An example of a temporal dataset series is a budget dataset series which groups together budget datasets for the years 2020, 2021, 2022 etc. ~~all referring to the same geographical area~~
- **Spatial dataset-series** - A series of datasets describing similar content of distinct geospatial coverage. An example of a spatial dataset series is a satellite mapping service showing crop mapping data ~~of a similar time frame and resolution but~~ of various geospatial coverage
- **Thematic dataset-series** - A series of datasets containing information on the same subject ~~and of temporal and spatial resolution~~, where each dataset focuses on distinct specific themes. An example of a thematic dataset series is a series of datasets collecting data on air pollutants ~~having the same spatial and temporal coverage but~~ where each dataset monitors levels of a different specific pollutant.

**Comment by init-dcat-ap-de** [comment]
Since DatasetSeries are a subtype of Datasets, should their type just be added to the dataset-type-vocabulary? Or should there be an additional vocabulary?

**Comment by bertvannuffelen** [comment]
@init-dcat-ap-de  these subclassing is a tricky thing. It does not mean that a current DCAT-AP dataset is a superclass of a DCAT-AP dataset Series. It still could be a distinct group. 

Note: This is currently the practice because a DCAT-AP catalogue is not a DCAT-AP dataset, because the semantics of the properties are different.
Personally I would not have introduced the subclassing of dataset to catalogue and datasetseries in DCAT.

**Comment by jakubklimek** [comment]
> Since DatasetSeries are a subtype of Datasets, should their type just be added to the dataset-type-vocabulary? Or should there be an additional vocabulary?

@init-dcat-ap-de I prefer a separate vocabulary to avoid (or at least discourage) the usage of the items such as "temporal series" with a dataset with multiple distributions as in https://github.com/SEMICeu/DCAT-AP/issues/240#issuecomment-1413923165

**Comment by bertvannuffelen** [comment]
On the different kinds of dataset-series:  Can we provide concrete examples of each case?
I know examples of the temporal case, but for the others I have no good real-life example yet.

**Comment by jakubklimek** [comment]
@bertvannuffelen 

- Spatial: https://data.gov.cz/dataset?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatové-sady%2F00025712%2F59ddccd404a617f695e3a1ef8e65b81e
- Topic/grouping: https://data.gov.cz/dataset?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatové-sady%2F00006947%2F4e7b6c4003ae1079dda2b7a56c93d248 (sorry for the metadata in Czech)

**Comment by bertvannuffelen** [comment]
@jakubklimek  thanks: it is good to have concrete examples.

**Comment by jakubklimek** [comment]
Another example of  **Temporal series with overlap**, i.e. **version series** could be versioned controlled vocabularies.

For instance, the [NUTS regions](https://ec.europa.eu/eurostat/web/nuts/history) - there are versions 2003, 2006, 2010, 2013, 2016, 2021. The versions have changes that are not only additive. Some regions are merged, some are split, some are cancelled etc., and some others are the same in all the versions.

This could be viewed as a DatasetSeries (NUTS) with the individual versions represented as Datasets.

The question is, is this distinct enough from a temporal series? I think it is, based on the overlap.

**Comment by init-dcat-ap-de** [comment]
As far as I can see, there is no solution in the current version of DCAT-AP 3.0.

**Comment by bertvannuffelen** [comment]
We propose to close this issue as during de past months it has become clear that there should be more evidence to support the needs for distinctions. And what these could be.
