### ISSUE TITLE
dcat:Distribution - use of dct:format and dcat:mediaType

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#26]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:format and dcat:mediaType
•	Usage: 12.17% and 25.52% respectively
•	Issue: dct:format is a recommended property but there are Distributions that use the optional property dcat:mediaType, which is more restrictive (IANA media type).
•	Is there a need for guidelines explaining how to use dct:format and dcat:mediaType similar to guideline “How to use accessURL and downloadURL?”, e.g. if specific media type(s) can be provided, duplicate value of the media type(s) in both dcat:mediaType and dct:format?

**Comment by makxdekkers** [comment]
The distinction made in the DCAT recommentation at W3C could be useful for automatic processing of distributions. The value of dct:format will not always be something that can be used to trigger some processing, while the value if dcat:mediaType is. In that sense it is very similar to the case of accessURL and downloadURL. It might therefore be a good approach also in this case to provide a guideline to use dct:format in all cases, irrespective of the value, and additionally provide dcat:mediaType if the value is one of the IANA media types.

**Comment by DGatt** [comment]
As a starting point for such a guideline consider the convention laid down in Germany's DCAT-AP.de implementation rules:

_If a file accessed with the AccessURL of a distribtion is of one of the MediaTypes listed int the MDR authority file table, this MediaType is to be entered under dct:format. If else, the MediaType must be denoted via dcat:mediaType using the IANA List (if necessary, a new entry can be created in this list._

Also taken into account should be the GeoDCAT-AP specification:

_The proposal is then to use the file type register of the Publications Office, if it includes the relevant format/media type, and the INSPIRE Media Types register otherwise._

**Comment by makxdekkers** [comment]
Proposed resolution | No change to the specification.

**Comment by addragan** [comment]
The issue will be closed and no changes will be done to the specification.
