### ISSUE TITLE
Cardinality for next/prev in Dataset member of a Dataset Series

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#263]
Issue for 
 - https://semiceu.github.io//DCAT-AP/releases/3.0.0#DatasetmemberofaDatasetSeries.next
 - https://semiceu.github.io/DCAT-AP/releases/3.0.0/#DatasetmemberofaDatasetSeries.previous

The cardinality is `0..*`. The usage note should explain, that it can only link to multiple `next`/`prev` if it is in mutiple Dataset Series.

Unless we really want to allow multiple `next`/`prev` in the same Dataset Series.

**Comment by bertvannuffelen** [comment]
Here I would like the advice of the community. 
In general I do not know if more complicated structures as a consequent list are needed (single next and single previous). 

Restricting the max-cardinality would have that impact. 

Since I do not have evidence for the need for this restriction, I propose that implementers first apply the specification and that we then evaluate if the restriction is too limiting.

**Comment by init-dcat-ap-de** [comment]
There could probably be tree or mesh structures as well...

I was looking for more guidance for our use case, but allowing everything and waiting to see if it's a problem is probably a good solution as well.
