### ISSUE TITLE
DatasetSeries subClassOf Resource instead of Dataset

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/DCAT-AP#289]
In [DCAT 3](https://www.w3.org/TR/vocab-dcat-3/#dcat-scope), `dcat:DatasetSeries` is a subclass of `dcat:Dataset`, which is a subclass of `dcat:Resource`.
In [DCAT-AP 3.0.0](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#DatasetSeries), it is just a subclass of `dcat:Resource`, which seems confusing.

**Comment by bertvannuffelen** [comment]
This issue is related to #278: see https://github.com/SEMICeu/DCAT-AP/issues/278#issuecomment-1710174225 .
And also the issue: https://github.com/w3c/dxwg/issues/1387

**Comment by terjesyl** [comment]
We see the implications listed below if `dcat:datasetSeries` is just a subclass of dcat:Resource. 

We would instead prefer that `dcat:DataSeries` is a subclass of `dcat:Dataset` as in DCAT. 

- 7.1 Defintion of property ‘type’: Agent is also used as publisher for Dataset Series and should be added. 
- 7.2 Definition of class Catalogue should be changed to: “A catalogue or repository that hosts the Resources being described.” 
- 7.2 Missing property on Catalogue: There is a property missing in the class Catalogue that links the Catalogue to the DatasetSeries. Without such a direct link, one has two options in order to find all DatasetSeries that are included in the Catalogue: 
  - Use the generic property dcat:resource which is not semantically precise. 
  - Follow the property dcat:inSeries in *all* Datasets, which may be a very resource-consuming operation. 
  - Possible solution: Add an optional 0..n property datasetSeries as a sub-property of dcat:resource 
- 10.2 dct:accrualPeriodicity: Should this also apply to the property dct:accrualPeriodicity in the classes “Dataset member of a Dataset Series” and “Dataset Series”?

**Comment by bertvannuffelen** [comment]
>     * 7.2 Missing property on Catalogue: There is a property missing in the class Catalogue that links the Catalogue to the DatasetSeries. Without such a direct link, one has two options in order to find all DatasetSeries that are included in the Catalogue:
>       

This topic was mentioned during the webinar on the alignment with DCAT 3.0.
The participants during the meeting did not consider this as a big issue as it could be inferred via querying.

We must highlight that DCAT 3.0 did not introduced this property. And therefore if the need is for such a property, the best place it to amend DCAT 3.0.  Otherwise  these core organisational properties are in two namespaces and that might lead to confusion.

**Comment by terjesyl** [comment]
To clarify, this is an issue only if Dataset is just a subclassOf Resource. I might be missing something, but how do you refer from a catalogue to a dataset series if DatasetSeries is just a subclass of Resource?

**Comment by matthiaspalmer** [comment]
In my view: An application profile cannot and should not try to redefine existing vocabulary with the help of RDFS. Furthermore, adding another `rdfs:subclassOf` relation between `dcat:DatasetSeries` and `dcat:Resource `does nothing as it is already implicit in this case.

Hence, having a statement in the textual document saying that it is a subclass of `dcat:Resource` rather than `dcat:Dataset` is misleading. In fact, I think this is nothing more / should not be considered as anything else than a minor bug in the current document.

**Comment by bertvannuffelen** [comment]
During Webinar 16 jan 2024 the embedding of DCAT-AP classes in DCAT has been explained. There were also 5 principles for writing DCAT-AP application profiles discussed that aid in the further design of DCAT-AP profiles.

**Comment by jakubklimek** [comment]
Indeed, during the webinar, it was explained that
1. DCAT-AP Dataset is subClassOf DCAT Dataset
2. DCAT DatasetSeries is subClassOf DCAT Dataset
3. but DCAT-AP DatasetSeries is not subClassOf DCAT-AP Dataset

So while I understand HOW this can be done in DCAT-AP, I still cannot find the reasoning behind WHY this is done in DCAT-AP. What are the reasons for not having DCAT-AP DatasetSeries subClassOf DCAT-AP Dataset?

**Comment by init-dcat-ap-de** [comment]
We would like to understand this as well.

Currently, following the DCAT-AP specification, a dcat:DatasetSeries would not have keywords. (Respectively, it is not easy to understand that they can have keywords.)
