### ISSUE TITLE
Clarification on Dataset Series as an ordered or unordered collection

### ISSUE THREAD

**Issue by terjesyl** [SEMICeu/DCAT-AP#296]
This issue is closely related to #278 but directed more towards Dataset Series in general, where I see the need for some clarifications. 

Does a series need to be ordered? Currently the profile seems to be ambigous with regard to the usage of Dataset Series.
- The definition of a Dataset Series (7.9) does not mention ordering of the collection: “A collection of datasets that are published separately, but share some characteristics that group them.”. 
- 18 (Example Dataset Series): the text after example 12 says that one should not diverge too far from dataset series as an ordered collection. 
- 7.8 (Dataset member of DatasetSeries) dcat:previous must exist for all but the last dataset in a collection. The definition of dcat:previous mentions an "ordered collection or series of resources", implying an ordering. 

If a Dataset Series can be an unordered collection, does it makes sense to require `dcat:prev`? In general I don’t think it would be natural to sequentially link the elements of an unordered collection. 

The way this is solved would be tigthly connected to how #278 is solved, but I see three alternatives: 
  - 1) The profile says that `dcat:prev` must be set for all series members except the last one in the chain. This requires all series to be ordered, whether there is a natural order for the collection or not (current requirement in profile). 
  - 2) The guidelines says that 
    - If the series is unordered, `seriesMember` must exist on the DatasetSeries to all its members (to make implementation computationally feasible), and
    - If the series is ordered, all members (except the last) has `dcat:prev`.
  - 3) The definition of Dataset Series is changed to reflect that the collection is required to be ordered.

(edit: typo)

**Comment by terjesyl** [comment]
Also related to #277

**Comment by nfreire** [comment]
I believe that the possibility to represent ordered and unordered dataset series is relevant for DCAT-AP.
Therefore, regarding the proposed solutions, I support option ii):
```
The guidelines says that:
If the series is unordered, seriesMember must exist on the DatasetSeries to all its members (to make implementation computationally feasible), and
If the series is ordered, all members (except the last) has dcat:prev.
```

**Comment by terjesyl** [comment]
@nfreire The only issue is the requirement from DCAT on inverse properties that says that dcat:inSeries must be present whenever dcat:seriesMember is used.

**Comment by bertvannuffelen** [comment]
This topic has been discussed during the november 2023 webinars. It was concluded that W3C Dataset Series can handle simple groupings but that more complex usages may lead to misinterpretations or distinct expectations.

Since the working group did not found a consensus on more precise expression of what is a Dataset Series, the consensus is to impose only a very minimal amount of constraints and stay close to W3C.
The drawback is that questions like the one here in the title: _being an ordered or unordered collection_ did not got an answer and that implementers have complete freedom. 
Broad harvesting portals must be ready to accept any possible case in the harvested data feeds.
