### ISSUE TITLE
HVD: explanation INSPIRE metadata

### ISSUE THREAD

**Issue by idevisser** [SEMICeu/DCAT-AP#309]
In the implementing regulation HVD is mentioned that The metadata describing the datasets within the scope of the INSPIRE data themes shall contain at least the metadata elements set out in Commission Regulation (EC) No 1205/2008.
In this document i expect some explanation how this requirement can be fullfilled.

**Comment by bertvannuffelen** [comment]
@idevisser This is beyond the current scope of DCAT-AP HVD. As annex of DCAT-AP, the document prescribes/describes how DCAT-AP can be used to fullfill the HVD IR requirements to the level it can capture.

With that I mean that DCAT-AP is about metadata, and not about the internal data structure. But it provide hooks so that an user can find that information. 
And we have read the HVD IR with the DCAT-AP language in mind. 

The result DCAT-AP HVD imposes a view/perspective on the metadata. It serves 2 purposes:

- harmonising the metadata description in DCAT-AP for HVD purpose so that they can be used to create reports based on commonly agreed queries on the DCAT-AP catalogue
- highlighting the metadata topics any domain must address.

And the latter objective is what you asked. How does INSPIRE ISO must be adapted to conform to/support the HVD IR?
DCAT-AP HVD provides for the INSPIRE metadata a target.

- Are the licences provided in INSPIRE machine readable and conform the approach expressed in DCAT-AP HVD?
- How does INSPIRE distinguishes between non-HVD dataset and a HVD dataset?
- How does INSPIRE expresses APIs and the contact points for these?    

DCAT-AP HVD offers thus the list of discussion topics each domain must consider.
But it is not sufficient, the HVD IR also imposes the presence of some data or some data structures. These have to be also address by the domain. Here DCAT-AP HVD will not help. 
Each domain can/must enrich DCAT-AP HVD with the additional rules or expectations to cover the HVD IR completely for itself.

This domain implementation can go as far as for instance: INSPIRE could define a validation service that would encode queries to be submitted to INSPIRE HVD APIs. Only when these validation service is giving green light, the HVD IR implementation for INSPIRE is correct. And this additional report could be integrated in the HVD reporting.  
I am not stating domain should be so strict, but in  the end a machine or human audit should be able to be made on all datasets and APIs to validate if they are really conform the HVD IR. 
For everything at this detailed level,  the domains have the main responsibility on facilitating that activity.

**Comment by idevisser** [comment]
I get the feeling that you have the impression that the referenced Commission Regulation (EC) No 1205/2008 is about data structure, but this is the [IR metadata](https://inspire.ec.europa.eu/documents/commission-regulation-ec-no-12052008-3-december-2008-implementing-directive-20072ec).

**Comment by bertvannuffelen** [comment]
Point taken. 

But here we are still on the edge between domain and generic. If the Commission Regulation No 1205/2008 mandates a different metadata requirements than the HVD, then I propose that INSPIRE-HVD is resolving this first prior introducing this in DCAT-AP HVD.

Also the  Commission Regulation No 1205/2008  only applies to some HVD data and DCAT-AP HVD has the intention to apply to all HVD domains. Thus one cannot apply the INSPIRE Commission Regulation to all other domains. This should be discussed with the domain responsibles.

The original objective of DCAT-AP HVD is to provide a uniform view on HVD requirements across domains.  If that is impossible due to conflicting regulations and existing agreements then this should be found out as soon as possible. Again I rely here on the INSPIRE community to explain how and when the  Commission Regulation No 1205/2008 is in conflict with DCAT-AP HVD.

For me is geoDCAT-AP the place where the details of mapping Commission Regulation (EC) No 1205/2008 to DCAT-AP has to be discussed. 
Let's suppose that geoDCAT-AP is aligned with the CR 1205/2008 then DCAT-AP HVD should be applied on top of geoDCAT-AP in order to provide the requirements for geospatial datasets subject to the HVD in the DCAT terminology. And this should be coherent approach. 

Personally, I need time to investigate the INSPIRE Regulation and which practical implementation agreements have been made in order to give a proper advice on INSPIRE related metadata. Given the experience in the INSPIRE community I have the hope that the community is able to clearly pinpoint the issues, rather than relying on an outsiders perspective who is possibly breaking all existing agreements.

**Comment by idevisser** [comment]
I wonder if you can separate the INSPIRE metadata requirements from the HVD metadata requirements; it is an HVD requirement for three themes that the metadata contain at least the metadata elements as set out in the IR metadata. Hence my initial question.

It is indeed not a requirement for all themes, which makes it more difficult to include it generically.

In my view, the data provider could find in DCAT-AP-HVD how he can offer his metadata in accordance with HVD. The generic part is now covered, but the theme-specific additional requirements are not yet covered. That seems to me to be the next step that needs to be taken to provide data providers with the necessary information.

Solving this via geoDCAT is a solution, but it may perhaps also be sufficient to refer to the full ISO metadata from the DCAT description.

It seems useful to me, when it comes to INSPIRE metadata, to work together with people from the INSPIRE community and people from the DCAT community.

**Comment by bertvannuffelen** [comment]
> 
> It seems useful to me, when it comes to INSPIRE metadata, to work together with people from the INSPIRE community and people from the DCAT community.
>
I fully agree.
