### ISSUE TITLE
RDF/XML file for DCAT-AP v3.0.0 is missing

### ISSUE THREAD

**Issue by Angatar** [SEMICeu/DCAT-AP#315]
Could you please add the RDF/XML version of the DCAT-AP v3.0.0 ?
It seems the JSON-LD context file provided cannot be imported into Protege.

**Comment by bertvannuffelen** [comment]
@Angatar what RDF file are you looking for? 

An RDF file containing all the information in the application profile is ambiguous. It would republish/redefine terms in other vocabularies. To avoid any confusion, such an RDF file is not being produced.


We are working on a updated publication of the new terms in DCAT-AP at http://data.europa.eu/r5r. This is currently in draft. It will only contain the terms in that namespace.
This is similar to DCAT. See  https://github.com/w3c/dxwg/blob/gh-pages/dcat/rdf/dcat3.ttl.

**Comment by Angatar** [comment]
Well, it seems that the DCAT-AP v2.1.1 and the previous ones had and RDF representation of the DCAT-AP, and I was looking for the equivalent file for DCAT-AP v3.0.0  ... https://github.com/SEMICeu/DCAT-AP/blob/master/releases/2.1.1/dcat-ap_2.1.1.rdf

However the interest of  DCAT-AP other DCAT is the definition of the cardinalities and I assumed the cardinalities would be present in the DCAT-AP RDF representation as well, it seems it is not the case.

So I assume my real question is rather: where can I find a DCAT-AP representation including the cardinalities that I could import as a basis in a project ontology?

**Comment by bertvannuffelen** [comment]
Indeed that was the case: the RDF somehow mimicked the html document, but very rudimentary. 

In the light of cleaner and relying on more correct publications we will not perform that one anymore, except for the new terms. See the [SEMIC styleguide](https://semiceu.github.io/style-guide/1.0.0/index.html).

The SHACL representation has taken over that role: there you find cardinalities.

Nevertheless if there is a good use case with a clear definition how the RDF representation should look like and this can be documented as profile.rdf we could consider it. 

However the problem is that a simplistic approach in RDF for profiles leads to difficulties. Consider the following examples

```
dcat:dataset a owl:objectProperty;
      rdfs:label "catalogue dataset"@en;
      skos:note "Example note: use this instead of dcat:resource"@en.  

dct:title a owl:dataProperty
    rdfs:label "title"@en
    skos:definition "the title of a dataset"@en, "the title of a distribution"@en, "the title of a catalogue"@en
```

The first is redefining the label of dcat:dataset, while the second is aggregating definitions from different local class scopes. While that aggregation for title is probably harmless, it is not for properties that require specific codelists as value space.  For that reason a simplistic RDF will not work.
A different RDF representation has to be created to capture that. And if you do so, you result in something similar to SHACL.

So happy to help, but from a specification point of view a simple RDF representation is difficult for a profile.

**Comment by Angatar** [comment]
Thanks for pointing out the [SEMIC styleguide](https://semiceu.github.io/style-guide/1.0.0/index.html) and the fact that the cardinalities are in the SHACL representation, it helps!

I get your point regarding the issues encountered with RDF for profiles.

However if  SHACL seems to be the right tool to define a list of constraints that can serve to validate a graph for applied constraints, I'd like to find a way to integrate these SHACL described constraints into my project ontology itself (that's why I was looking for a rdfxml or owl2 representation that includes the constraints and not a separate list of constraints that can validate a graph).

SHACL is new to me ... maybe there are more adapted tools than "Protege + its SHACL pluggin", to make this work, or maybe I didn't made it work properly.
The SEMIC guidelines seems to point towards UML as a bridge/pivot but how to turn it automatically into an ontology with cardinalities included?

Could you indicate me more appropriate tools or a way to proceed to integrate the DCAT-AP constraints directly into my project ontology and not as a sidecar list of SHACL constraint specifications?
We are starting from scratch and thought DCAT/DCAT-AP can serve as a good basis.

**Comment by bertvannuffelen** [comment]
> 
> SHACL is new to me ... maybe there are more adapted tools than "Protege + its SHACL pluggin", to make this work, or maybe I didn't made it work properly. The SEMIC guidelines seems to point towards UML as a bridge/pivot but how to turn it automatically into an ontology with cardinalities included?
> 
The SEMIC styleguide is about creating vocabularies and application profiles in such a way the resulting artefacts can be reused in building new specifications in a semantically coherent way. They start from the need to have all artefacts that are being created in that editorial process to be coherent. In addition the styleguide takes the assumption that one wants to have an editorial toolkit that automatically generates these artefacts (instead of manual editing). Given the fact that one wants to create an meaningful diagram and that what is on the diagram is also present in the html/rdf/shacl/jsonld/... artefacts the styleguide has been written from the notion of a conceptual model expressed in the UML class diagram language.


>
> Could you indicate me more appropriate tools or a way to proceed to integrate the DCAT-AP constraints directly into my project ontology and not as a sidecar list of SHACL constraint specifications? We are starting from scratch and thought DCAT/DCAT-AP can serve as a good basis.
>
For this: what is the objective of your activity: a) create a new profile or b) an editor for instances of DCAT-AP?
These are very different things and have different answers.

As earlier written the RDF and even OWL language are not very friendly in case of profiling. The only approach that would match the direct encoding would be to create subclasses of each class and start from that. In this way the scoping becomes tangible. 
So far that approach has not been promoted, nor applied in application profiles because it feels counter-intuitive and it will raise additional questions how to handle this in implementations and harvesting networks. But probably it is the only approach if one would like to stick to RDF/OWL. 

This "profiling" expression is a topic of upcomming webinar in november.

**Comment by Angatar** [comment]
> For this: what is the objective of your activity: a) create a new profile or b) an editor for instances of DCAT-AP?
> These are very different things and have different answers.
Actually, our project objectives are to gather different partner projects information, bringing consistency by structuring the metadata and uniforming the standards so that we can expose it as harvestable catalog of data notably through the use of the DCAT-AP. So, we intended to start by identifying the minimal metadata required from each project and selecting preferred standards as well as cross references and creating a [project ontology](https://oboacademy.github.io/obook/tutorial/project-ontology-development/) to support the metadata selection process, the interoperability of metadata and standards and help to ensure a certain semantic consistency. The aim of the inclusion of the cardinalities into the ontology was to permit to distinguish mandatory metadata from optional metadata. 
So, I would say that the initial objective of our current activity is rather to create something that will be an instance of DCAT-AP, but I'm discovering the profile aspects and it might be something we could consider in a second intention.

>This "profiling" expression is a topic of upcomming webinar in november.
Great! I'll try to attend... where can I find more details on the event?

**Comment by bertvannuffelen** [comment]
you can find all details on this webinar and its earlier one on joinup: https://joinup.ec.europa.eu/collection/semic-support-centre/events.  For this the dedicated info is at https://joinup.ec.europa.eu/collection/semic-support-centre/event/webinar-dedicated-technical-issues-related-dcat-ap.

**Comment by Angatar** [comment]
Thanks!
I'm closing this now but might be back soon with more technical issues  ;)
