### ISSUE TITLE
Is there DCAT-AP 2.2.0?

### ISSUE THREAD

**Issue by fabiankirstein** [SEMICeu/DCAT-AP#324]
The DCAT-AP HVD specification is released under the [version 2.2.0](https://github.com/SEMICeu/DCAT-AP/tree/master/releases/2.2.0-hvd). However, DCAT-AP HVD is labeled as an extension to DCAT-AP, applicable to version 2 and 3.  

Is there a standalone version of DCAT-AP 2.2.0? The last release seems to be 2.1.1.

**Comment by bertvannuffelen** [comment]
@fabiankirstein, indeed the numbering has been based upon some historic activities. We created a draft in the past of a version DCAT-AP 2.2.0 which included some bugfixes and the first html represenation of DCAT-AP. However during the webinars of 2023 this version got intertwined with the alignment of DCAT 3. Therefore it has been decided to publish a version of DCAT-AP 3 (draft) rather than a DCAT-AP 2.2.0 plus a DCAT-AP 3.0. By then, the numbering of DCAT-AP HVD was already associated with the improvements to DCAT-AP 2.1 (more precisely: the additional explanations on Legal Information).

When DCAT-AP 3 gets released we will prepare also an editorial release of DCAT-AP HVD to align the version numbers.

I hope this clarifies the numbering.

**Comment by fabiankirstein** [comment]
Thanks @bertvannuffelen! To summarize, there is nothing in DCAT-AP 2.2.0 besides the HVD additions, that is not in 2.2.1?

**Comment by bertvannuffelen** [comment]
correct.
