### ISSUE TITLE
DCAT: Dataset – Suggestion attribute for record - ‘maintainer’ 

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#39]
Def:
Person, who maintains a dataset; is responsible for it and its publication

Datatype: rdfs:Literal string 

Reasoning for change:  
The maintainer (such as the curator) cares for the dataset and is in charge for keeping metadata up to date. This concept was added in dcat-ap.de as the existing ones were found not to be appropriate.

**Comment by akuckartz** [comment]
:-1: regarding range rdfs:Literal

**Comment by giorgialodi** [comment]
In the profile there is a class Agent to be used in order to identify an Agent that has a specific role on the dataset. I would suggest not to use as range an rdfs:Literal. 
In the Italian profile DCAT-AP_IT, in addition to the publisher, that should be responsible for the publication, we added the "rightsHolder" and the "creator" (properties from Dublin Core). 
Specifically, there might be one or more creators, but there is one clear rights holder on the dataset that has the responsibility on the content of the dataset itself (actually there are cases in which there might be more than one rights holder). This is especially true in our country, in all the cases in which Regions support their local municipalities in the publication of (open) datasets. In this case, the rights holder is the municipality whereas the publisher is the Region.

**Comment by akuckartz** [comment]
Agent roles were discussed in https://joinup.ec.europa.eu/discussion/add-dctcontributor-dataset and https://joinup.ec.europa.eu/discussion/geodcat-ap-how-express-different-responsible-party-roles-supported-iso-19115-inspire

**Comment by makxdekkers** [comment]
@init-OGD It looks like the definition you suggest is quite close to the definition of dct:publisher: "An entity responsible for making the resource available." In general, people could expect the publisher to also maintain the Dataset.

**Comment by makxdekkers** [comment]
Proposed resolution | No change.

**Comment by bertvannuffelen** [comment]
Also for more roles we should consider the approach of geo-DCAT-AP. There the issue of roles and parties has been addressed.

**Comment by NatasaSofou** [comment]
No change as one comment objected to the proposed range of rdfs:Literal. Further comments that on DCAT-AP discussed agent roles. The definition of “maintainer” is very close to semantics for “publisher”.

**Comment by init-dcat-ap-de** [comment]
In our German case often the publisher is the ministry while the maintainer is an agency or even a company mainting on behalf of the publisher the dataset.
