### ISSUE TITLE
dcat:Catalog - remove dct:language?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#4]
The DCAT-AP usage analysis on the European Data Portal showed the following:

dct:language
•	Usage: 0%
•	Should this property be removed/withdrawn/deprecated?

**Comment by akuckartz** [comment]
What exactly would be the implications of each of the three alternatives and the fourth one (no change)?

That question applies to the other issues as well.

**Comment by giorgialodi** [comment]
Nice question of @akuckartz :) BTW: for the dcat:Catalog there might be cases in which the catalogs are available in more than a language. In Italy this applies. Here are two examples: http://daten.buergernetz.bz.it/it/catalog.rdf (the catalog is available in German and Italian, two official languages in some Italian Regions in the north border) and http://dati.beniculturali.it/sparql?default-graph-uri=&query=construct+%7B%3Fs+%3Fp+%3Fo%7Dwhere%7Bgraph+%3Chttp%3A%2F%2Fdati.beniculturali.it%2Fdescrizione_dataset%3E+%7B%3Fs+%3Fp+%3Fo%7D%7D&format=application%2Frdf%2Bxml (in this case the catalog is available only in Italian but the language property is used). In general in the DCAT-AP_IT profile we recommend the use of the property.

**Comment by makxdekkers** [comment]
As far as I look at it, there is no real difference between the three options in terms of consequences for interoperability. There could be a difference in terms of documentation: 'removed' properties would simply be no longer mentioned in a new version of the profile, while 'withdrawn' or 'deprecated' properties could be mentioned with some sort of warning, not to use the property anymore, but to expect that some existing data might include it. I don't see much of a difference between withdrawing and deprecating -- withdrawing sounds a little softer like a suggestion, while deprecating sounds more like a strong discouragement -- in the end, the implication is the same.
The implication in all three cases is that a harvester would not expect the property to appear in DCAT-AP metadata, and if it does, the harvester could just ignore it.

**Comment by bertvannuffelen** [comment]
I in general like the number of fields as they have mostly some good definitions and are there to support some usecases. 

They are rightly mostly annotated as optional, as the effort to give good values to them (and maintain it) requires effort.
The statistics shown by each of the issues are for me indications of two problems:
   a) the definition did not fitted well, and hence not used
   b) the data could not be collected (for what ever reason)

Removing the properties to those that most portals are providing has potential impact on the usability of the catalogue. 
I think we should consider what are the target audiences for the catalogue and the see if the data provided is aiding to achieve that purpose. Today's open data portals mostly are oriented to accidental visitors who want to know what data exists and a bit browse through it. The catalogues are seldom used as a navigator to the technical audiences which would use the catalogues as their source to combine the actual data.
In order to do so technical properties as checksums, formats, sizes, api descriptions are needed.
And maybe this is a discussion worth: how can DCAT-AP handle more consistently the different dissemination forms and provide a highlevel description for it so that this data integration can be realized.
It would be great if we could come to an extension approach so that this can also lead to good interoperability.  I am aware that this has it limits from the perspective of DCAT-AP, but if taking the perspective of the developers, self-descriptive services/distributions are what they ask for. In my opinion, it would be fantastic if it would be clarified how this bridge is made. 

kr,

Bert

**Comment by makxdekkers** [comment]
Bert, the issue of how DCAT can better support data integration is also discussed in the DXWG group at W3C. See for example https://www.w3.org/TR/dcat-ucr/#ID7 and https://www.w3.org/TR/dcat-ucr/#ID26. It seems to me that if DXWG finds a solution for it, the DCAT-AP group could consider adopting that approach.

**Comment by makxdekkers** [comment]
Created new issue https://github.com/SEMICeu/DCAT-AP/issues/35 for comment from https://github.com/bertvannuffelen.

**Comment by makxdekkers** [comment]
On the issue of dct:language for Catalogue, the comment from @giorgialodi indicates that the property should not be deleted from the profile.

**Comment by makxdekkers** [comment]
Proposed resolution | No change.

**Comment by addragan** [comment]
Issue rejected due to disagreement comments. The issue will be closed with no changes in the specification.
