### ISSUE TITLE
Missing link between checksum class (value) and sum-checked distribution (accessURL?)

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/DCAT-AP#49]
When working on [https://www.dcat-ap.de/](url) we encountered a missing link between the binary file described in the distribution and its checksum value in RDF:
If you serialize into RDF -  so if you do not use the XML hierarchical structure - it is not clear which checksum value is associated with which file in which distribution. The problem occurs as order of things cannot be granted by the XML processor and Distributions and Checksums are two independent classes with a currently missing link and the rdf:nodeID is optional and not sure what to put into it to create this linkage.

Perhaps the use of the dataset dcterms:identifier or the distributions accessURL ( following the logic in [https://joinup.ec.europa.eu/release/dcat-ap-how-use-identifiers-datasets-and-distributions](url) ) as a checksumClass rdf:nodeID statement might be a workaround for this and can be added when reworking the spdx vocabulary or somehow be considered in the current ISA² DCAT-AP review?

**Comment by addragan** [comment]
Proposed resolution: Add property Dataset dcterms:identifier or Distributions dcat:accessURL as a checksumClass rdf:nodeID. Please comment preferred option.

**Comment by jakubklimek** [comment]
`rdf:nodeID` is a blank-node identifier specific to the RDF/XML serialization, it does not solve the inherent issue in the RDF modeling, which is, that a single `dcat:Distribution` can point to multiple files using `dcat:accessURL` and `dcat:downloadURL`, and there is no further metadata for those files.

In the Czech Republic, for instance, we only allow one value of `dcat:downloadURL`, so that all metadata attached to the distribution applies to that one file. Then, we have no such problem, as the only checksum attached to the distribution is the checksum of the only file referenced in `dcat:downloadURL`.

@init-dcat-ap-de Do you have a use case where you need multiple files to be referenced from a single distribution, in contrast to having multiple distributions/datasets each pointing to a single file, therefore allowing for a better metadata description of each cataloged file?

**Comment by init-dcat-ap-de** [comment]
Using rdf:nodeID might help us.
We do not have use cases where accessURL points to several files. If so, we would zip those files and create the hash algorithm value on the ZIP-file.

**Comment by jakubklimek** [comment]
@init-dcat-ap-de OK, that's two EU countries. Then maybe DCAT-AP could define a restriction that `dcat:accessURL` and `dcat:downloadURL` can have only one value, which could help even more.

**Comment by init-dcat-ap-de** [comment]
see: https://github.com/SEMICeu/DCAT-AP/issues/93#issuecomment-544282897

**Comment by sandervd** [comment]
In #79 the properties dcat:compressFormat and dcat:packageFormat will be added to the Distribution  class, the same cardinality problem will arise there.

**Comment by bertvannuffelen** [comment]
Basically the problem comes down to the fact that many of the properties of a Distribution become technical unusable in case there are multiple downloadURL references. Checksums, formats, packageformat, language, etc... have no "technical operational value" in case one cannot relate the value of a checksum with a download value. 

The fact there are many distributions is as such not an issue for the catalog. It is an issue for the editor (who might not have not have have the support to create quickly many variants) or an issue of the Data Portal to present the amount to the user. 

The original request was made with the mindset that the semantics of properties such as checksum are only meaningful when there is one physical resource available. 

As stated in https://github.com/SEMICeu/DCAT-AP/issues/49#issuecomment-514938073 the multiple variants can be grouped under one Distribution description by zipping the content in one file. 
In https://github.com/SEMICeu/DCAT-AP/issues/93#issuecomment-544282897 the same author mentioned a case where splitting might be useful in case of large files, but again today large file sharing tools exists.  

A note on the harvesting case, Normally I would expect that the harvesting portal is not merging distributions from 2 catalogs. If so, the merging process should anyhow have smart tactics how data from one distribution with another can be brought together. Such a decision process should be able to lead to a unique Distribution with a single downloadURL.

**Comment by bertvannuffelen** [comment]
proposed resolution: to keep the original request for a stricter cardinality.

**Comment by matthiaspalmer** [comment]
I am very much against this resolution to restrict dcat:downloadURL to a single value.

There was a long discussion on the [DCAT2 issue 868](https://github.com/w3c/dxwg/issues/868) regarding how to work with data series and I have there outlined one possible solution, i.e. to repeat dcat:downloadURL.

Since this discussion has not been resolved and is tagged as future work, I would prefer that DCAT-AP does not make a premature decision and invalidate one possible solution. At least not without discussing the consequences in more detail.

From a tool developers perspective, I would prefer to change the implementation when there is a permanent solution (if it is different). To be forced to invent another temporary solution and then change it again when the DCAT 3 arrives is just a waste of time. 

@bertvannuffelen from the perspective of data-series only checksum constitutes a problem. From my pragmatist perspective, I do not think we have a singe dataset with checksums in Sweden, but many that use repeated downloadURLs. So, just leaving out checksums if you repeat dowloadURLs is a viable option. If you really need to provide a checksum, then use the other mechanism and provide a zip. And yes, always zipping files together is an option, but that means being forced to implement a temporary workaround until DCAT 3 provides a better solution, which is what I want to avoid.

**Comment by bertvannuffelen** [comment]
@all, after reconsulting the issue, the cardinality of dcat:downloadURL and dcat:accessURL will remain the same and  this topic will the added to the future-work list.
