### ISSUE TITLE
dct:language - Incoherence between the class diagram and the SHACL shapes

### ISSUE THREAD

**Issue by Maxservais** [SEMICeu/DCAT-AP#55]
In  the diagram of DCAT-AP 1.2 dct:language points to dct:LinguisticSystem while in the SHACL shapes it points to a skos:Concept

**Comment by makxdekkers** [comment]
Please note that it is not _wrong_ to link to a skos:Concept as long as there is no explicit statement that skos:Concept is disjoint with dct:LinguisticSystem. From the definition of dct:language you may infer that the object is an instance of dct:LinguisticSystem, even if it doesn't explicitly say so.

**Comment by makxdekkers** [comment]
But of course it is wrong for the SHACL shape to _require_ the object to be an instance of skos:Concept.

**Comment by addragan** [comment]
Proposed resolution: Update SHACL by aligning dct:language to dct:LinguisticSystem.

**Comment by sandervd** [comment]
@makxdekkers 
Could you elaborate on the why it would it be wrong to require the shape to restrict the range to skos:Concept?
> From the definition of dct:language you may infer that the object is an instance of dct:LinguisticSystem, even if it doesn't explicitly say so.

As the classes are indeed not disjoint, why not further close the world in the shape to better represent the intention of the specification? I would go as far as defining that the concept must belong to the right concept scheme?
As the written documentation already requires the use of the MDR codelist, I would prefer the SHACL shappes to follow this reality (if the intention is to use the shapes in an operational context for validation in data exchange)?

**Comment by makxdekkers** [comment]
@sandervd As I see it, you can't just require a property to have a range that is different from the range asserted by the specification that defines it. Imagine that you want to use a URI for a language that is defined as an instance of the class `dct:LinguisticSystem` and not of `skos:Concept`. The SHACL that requires an instance of `skos:Concept` would flag it as a violation which is obviously an incorrect result.
I don't think you can do such a thing, "_to better represent the intention of the specification_" -- if you feel that the specification does not correctly capture the intention, a change request should go to the owners of the specification, in this case DCMI.

**Comment by sandervd** [comment]
> I don't think you can do such a thing, "to better represent the intention of the specification"

I should have been more concise. I was intending at referring to the application profile here.
The application profile states that the range is, in fact a skos:Concept.

But I have the feeling our disagreement is more fundamental than this. 
I'll try to explain my perspective. For me, the big value of the SHACL shapes is when I can use them in an operational context. 
If DCAT-AP expects that the dct:language points to a skos:Concept in a controlled vocabulary, then I would expect applications producing DCAT-AP data to comply with this. The proposed solution of changing the range to dct:LinguisticSystem for me doesn't make a lot of sense.
The whole point of SHACL is to close the world so that we can use the AP for data exchange, instead of as merely a form of documentation.

**Comment by makxdekkers** [comment]
> If DCAT-AP expects that the dct:language points to a skos:Concept in a controlled vocabulary, then I would expect applications producing DCAT-AP data to comply with this. The proposed solution of changing the range to dct:LinguisticSystem for me doesn't make a lot of sense.

As far as I can see in the specification, in all places where `dct:language` appears its range is given, correctly, as `dct:LinguisticSystem`, not `skos:Concept`. The fact that the terms in the controlled vocabulary http://publications.europa.eu/resource/authority/language are defined as instances of the class `skos:Concept` does not change the range of the property. By using the terms in the Language NAL as objects of `dct:language`, those terms can be inferred to be _also_ instances of `dct:LinguisticSystem`. Of course, it would be the most elegant solution if the Publications Office could declare those terms to be also instances of the class `dct:LinguisticSystem`, in which case this discussion goes away.
I don't think that DCAT-AP should expect that the object of `dct:language` is an instance of  `skos:Concept` in a controlled vocabulary -- it should expect the object to be a language, even if it is represented by a `skos:Concept`.

**Comment by costezki** [comment]
Question: Why not publish language table as a list of `dct:LinguisticSystem` instances? Or, conversely, why not making authority tables more specific than skos:Concept? For example, why not publishing the individuals in the Languages table as instances of `dct:LinguisticSystem`, `gold:Language`, `lvont:Language` etc. 

Answer: Because this would quickly introduce problems in specific scenarios. Keeping the entities general enough (i.e. skos:Concept) permits wider adoption thus fulfilling the goal for controlled vocabularies.

### Some concerns
* dcat-ap: needs to be consistent with the model. If the range of a property is `dct:dct:LinguisticSystem` then the formal constraint shall reflect that, and implicitly the values shall be instances of this class. 
* controlled vocabularies (e.g languages authority table): need to be as generic and agnostic as possible, thus committing to as few models and constraints as possible. 

### what could be done? 
Create a helper class with an `extensional` definition; that is to define classes by specifying the individuals it is composed of. This class is non-intrusive that requires no changes neitehr in the controlled vocabulary nor in the other models. 

In Cellar this problem is solved as follows:
* define a new class `euvoc:Language`, which is equivalent to the extent of the concept scheme `mdr-nal:language` (currently published authority table). 
* this class is a subclass of skos:Concept, i.e. each instance of this class is also a skos:Concept (which is already provided in the published authority table).
* in addition, the solution for us, this class can be a subclass of as many classes as needed to cover the specific scenarios. 

This class (defined in EuVoc ontology that is part of the Cellar CDM ontology) is an artifact that on one hand is well-scoped by the controlled vocabulary and on the other hand connects to existent standards without directly imposing any standard on the controlled vocabulary. Formally it would look like this: 

```Turtle
euvoc:Language
    rdf:type owl:Class ;
    rdfs:label "Language" ;

    # anything that is in [that scheme] is also an instance of [this class]
    owl:equivalentClass [
        rdf:type owl:Restriction ;
        owl:hasValue mdr-nal:language ; # the OP/MDR Language concept scheme
        owl:onProperty skos:inScheme ;
    ] ;

    # anything that is an instance of this class is also an instance of the following classes
    #rdfs:subClassOf skos:Concept ; # needed in Cellar, but redundant in this context
    rdfs:subClassOf dct:LinguisticSystem ; # useful for DCAT-AP
    #rdfs:subClassOf lvont:Language ; # useful to other context 

    rdfs:comment """ This class (defined in EuVoc ontology that is part of the Cellar CDM ontology) is an artifact that on one hand is well-scoped by the controlled vocabulary and on the other hand connects to existent standards without directly imposing any standard on the controlled vocabulary. """ ;
.
```

In DCAT-AP this could be solved as follows:
```Turtle
dcat-ap:Language
    rdf:type owl:Class ;
    rdfs:label "Language" ;
    rdfs:subClassOf dct:LinguisticSystem ; # useful for DCAT-AP
    owl:equivalentClass [
        rdf:type owl:Restriction ;
        owl:hasValue mdr-nal:language ; # the OP/MDR Language concept scheme 
        owl:onProperty skos:inScheme ;
    ] ;
.
```

### Note:
mdr-nal: <http://publications.europa.eu/resource/authority/>
lvont: <http://lexvo.org/ontology#>
euvoc: <http://publications.europa.eu/ontology/euvoc#>
skos: <http://www.w3.org/2004/02/skos/core#>

**Comment by bertvannuffelen** [comment]
To resolve this issue we should agree on how we are doing validation and inference. Because of the definition by dublin core, the SHACL constraint must state that the range of dct:language is a dct:LinguisticSystem.

**option a)**
It must be explicitly specified in the RDF graph which is obtained from combining the catalogue under consideration, the mdr-nal and the ontologies which are mentioned in DCAT-AP. 

Under this approach the SHACL constraint will fail. 

_solution_: explicit adaption to the mdr_nal to explicitly state the membership. But since this is not the only case, it would reduce the realisation potential of this option.

**option b)**
Relying on the open-world semantics and logical implication semantics: because the only case in which this constraint is true is when it satisfy the membership of dct:LinguisticSystem, and nothing is present in the RDF graph that would lead to a defeat of that statement it must be true. 

Problem with this approach is that any value will always be acceptable. Hence this solution is not desired.

**option c) **
Explore the inference options in SHACL to make all items of the mdr_nal member of the dct:LinguisticSystem. One of these options can be the helper class approach by @costezki. 

_solution_: This is probably the cleanest approach that could lead to a solution. It is the implementation of the statement that the codelist mdr_nal should be used.

**Comment by bertvannuffelen** [comment]
resolution: made the SHACL shapes correspond as close to the DCAT-AP specification with a minimal amount of additional constraints that would blocked a future solution.

**Comment by bertvannuffelen** [comment]
In draft release 2.1.0 (https://github.com/SEMICeu/DCAT-AP/tree/2.1.0-draft/releases/2.1.0), according to discussions on SHACL, a splitted version of SHACL shapes. 

It allows more freedom for implementors to choose their desired "inference"/"validation" interpretation.

**Comment by bertvannuffelen** [comment]
Since no additional comments the proposed resolution is considered to be accepted.
