### ISSUE TITLE
dcat:Catalog - remove dct:isPartOf?

### ISSUE THREAD

**Issue by brechtwyns** [SEMICeu/DCAT-AP#6]
dct:isPartOf and dct:hasPart
•	Usage: 0%
•	Should this property be removed/withdrawn/deprecated?

**Comment by makxdekkers** [comment]
Proposed resolution | Remove dct:isPartOf from Catalog.

**Comment by NatasaSofou** [comment]
It was decided to keep this property in the model for now.

**Comment by akuckartz** [comment]
Who decided that?

**Comment by addragan** [comment]
@akuckartz All issues are evaluated by the DCAT-AP editors first (currently @addragan & @NatasaSofou) and discussed within an internal meeting with the SEMIC project officers.  The proposed resolution is then presented on GitHub and remains open for discussion until a consensus is reached and the fix is included in the next appropriate release.
