### ISSUE TITLE
Add new class  dcat:DataService, as a subclass of dcat:Resource 

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#73]
Add new class  **dcat:DataService,** subclass of dcat:Resource, as a collection of operations that provides access to one or more datasets or data processing functions, with properties:

- dcat:servesDataset : A collection of data that this data service can distribute.
- dcat:endpointURL: the root location or primary endpoint of the service (an IRI 
- dcat:endpointDescription: A description of the services available via the end-points, including their operations, parameters etc
- dct:license: A legal document under which the service is made available.
- dct:accessRights: Access Rights MAY include information regarding access or restrictions based on privacy, security, or other policies.

**Comment by oystein-asnes** [comment]
+1 from Norway to include both `dcat:DataService` and `dcat:Resource` as new classes. FYI: The question raised on formats for `dcat:DataService` on the august webinar is now raised here: https://github.com/w3c/dxwg/issues/1055

**Comment by jakubklimek** [comment]
+1 from Czechia for inclusion in DCAT-AP. The support for services is broader than just geoservices.

I think GeoDCAT-AP (1.0.1) representation of services will need to be changed according to the development in DCAT 2 and, subsequently, DCAT-AP. 

GeoDCAT-AP originally had to cope with the missing support for services in DCAT-AP, and IMHO not in a nice way. When there is proper support for services in DCAT-AP, a GeoDCAT-AP update will be able to adopt and, if necessary specialize this generic approach.

**Comment by NatasaSofou** [comment]
Proposed resolution: add dcat:DataService to DCAT-AP

**Comment by matthiaspalmer** [comment]
I think it is unclear what the range of dct:accessRights is supposed to be. The specification document is currently rather vague. The DCAT2 has a section discussing [license and rights](https://w3c.github.io/dxwg/dcat/#license-rights) outlining three options where the use of dct:accessRights seems to be very much along the lines of how it is used on dcat:Dataset. I.e. with the three options public/non-public/restricted that outlines if the dataset can be accessed by anyone or it requires specific authorization.

Hence, I would assume the same is the case for dct:accessRights on the dcat:DatasetService. But since the text in the specification is not formulated the same way (does not refer to the same controlled vocabulary) the reader is left wondering.

Unless there is another intention I suggest to specify that the same vocabulary should be used.

**Comment by bertvannuffelen** [comment]
@matthiaspalmer there will be future discussions on the usage of accessRights and licences. I close this issue as your concern will be tackled there.
