### ISSUE TITLE
Add prov:wasGeneratedBy  to dcat:Dataset

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#75]
Class dcat:Dataset,  add  property prov:wasGeneratedBy to specify an activity that generated, or provides the business context for, the creation of the dataset.

**Comment by NatasaSofou** [comment]
Proposed resolution: add  optional properties:

- prov:wasGeneratedBy
- prov:qualifiedAttribution
- dct:creator

**Comment by bertvannuffelen** [comment]
resolution: accepted

**Comment by matthiaspalmer** [comment]
It is unclear from the specification how to express the prov:qualifiedAttribution, DCAT2 is more clear with examples. I think it should be clarified that prov:Attribution is supposed to have two properties, dcat:hadRole and prov:agent.

In addition, it is discussed how the previous expression in GeoDCAT-AP used dct:type, but it does not state explicitly that the dcat:hadRole is now preferred instead (which it is, right? otherwise it would be incompatible with DCAT2).

I think prov:Attribution should be listed in section 4, just like dcat:Relationship is.

**Comment by matthiaspalmer** [comment]
I think it makes sense to restrict the cardinality of dct:relation and dcat:hadRole in dcat:Relationship.
The same for prov:agent and dcat:hadRole in prov:Attribution.
