### ISSUE TITLE
Align properties  in dcat:PeriodOfTime  with DCAT 2

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#83]
Add properties dcat:startDate, dcat:endDate instead of schema:startDate, schema:endDate to align with [DCAT 2](https://www.w3.org/TR/vocab-dcat-2/#Class:Period_of_Time) properties

**Comment by NatasaSofou** [comment]
Proposed resolution: Add dcat:startDate, dcat:endDate as recommended, instead of schema:startDate, schema:endDate to align with DCAT 2

**Comment by andrea-perego** [comment]
As I already said, it is important to take into account backward compatibility. So, if `dcat:startDate` and `dcat:endDate` are made recommended, an indication should be included about the equivalent properties currently used. Are they optional? or deprecated?

**Comment by init-dcat-ap-de** [comment]
We have data that uses the "old" schema properties for periodOfTime, so we would prefer to set it to "deprecated" for the next version.

**Comment by bertvannuffelen** [comment]
Since the change is not a deprecation of the properties _startDate_ and _endDate_ but a URI replacement existing catalogues will not become invalid. Merely systems would not pick up the values anymore.

resolution: add a shape file with a check on the properties to inform catalogue owners of the existence of the old URIs.
