### ISSUE TITLE
::CatalogRecord adms:status  and ::Distribution adms:status 

### ISSUE THREAD

**Issue by NatasaSofou** [SEMICeu/DCAT-AP#86]
- ::CatalogRecord adms:status-> This property refers to the type of the latest revision of a Dataset's entry in the Catalogue. It MUST take one of the values:  :created, :updated or :deleted depending on whether this latest revision is a result of a creation, update or deletion. It is controlled by ADMS change type vocabulary (which doesn't exist)

- ::Distribution adms:status -This property refers to the maturity of the Distribution, it is controlled by ADMS status vocabulary http://purl.org/adms/status/. 

The case here is that we have the same property in two different classes, with different definitions.  If we refer to the same thing, the definitions must be aligned and 
ADMS status vocabulary must be used for both.

If the property in CatalogRecord is about change type, then the property should be changed and a different property name should be used.

**Comment by init-dcat-ap-de** [comment]
We think adms:status should be kept for both an the definition and values should be aligned to the version in Distribution.

**Comment by bertvannuffelen** [comment]
This topic might be even more complicated to resolve as we have incompatabilities with between the definitions in the vocabulary adms (https://joinup.ec.europa.eu/release/adms-ap-joinup-version/20) and the one in DCAT-AP.

definition adms:status property in de pdf document are

-  (Asset)  _status of the Asset in the context of a particular workflow process, using a controlled vocabulary (see section 8.1)_
-  (Distribution) _status of the Distribution in the context of a particular workflow process, using a controlled vocabulary (see section 8.1)_

definition adms:status property in the RDF is 

- _Status of the Asset in the context of a particular workflow process, using a controlled vocabulary - ADMS Status vocabulary >> http://purl.org/adms/status/_ 

definitions in DCAT-AP are

-  (DatasetRecord) _This property refers to the type of the latest revision of a Dataset's entry in the Catalogue. It MUST take one of the values :created, :updated or :deleted depending on whether this latest revision is a result of a creation, update or deletion._
-  (Distribution) _This property refers to the maturity of the Distribution_

In addition we have to realize that this is a specific DCAT-AP 1.x addition. As a corresponding property does not exists in DCAT 2.0. It only suggests to use Prov-O to express evolution traces. And in Prov-O there is no corresponding property & associated codelist because it defines the notions create, update, remove as activities (Classes). That is a more flexible model.

**Comment by bertvannuffelen** [comment]
proposed resolution: 

Given the labels are different and the definitions are different, the intentions might be different. This is best clarified out. Secondly, the enforcement of the codelist by adms:status (see RDF definition) makes that only these codes can be used. And as original definition for the catalog record _change_type_ already indicated there might be need for more appropriate codes. 

Therefore, the proposal is to do a minimal change now for release 2.0. by removing the reference to the possible values. I propose to do the same on page 17 for the Distribution. 

And put this as an discussion topic for a future release for DCAT-AP 2.x

**Comment by andrea-perego** [comment]
I don't remember if this has already been discussed, but an option for a future release of DCAT-AP is to look into the relevant NALs from EU Vocabularies:
- Dataset status: https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/dataset-status
- Concept status. https://op.europa.eu/en/web/eu-vocabularies/at-concept-scheme/-/resource/authority/concept-status

The Dataset status NAL has the same values of ADMS status, so it could be an alternative, if need be, for distributions (despite it refers to the status of a dataset).

The Concept status NAL is more elaborated, and it is probably fit for catalogue records, which have a workflow similar to the ones used for items in a registry.

For the records, the support in DCAT to the notion of "resource status" (possibly by using `adms:status`) is currently being discussed in the W3C DXWG - see https://github.com/w3c/dxwg/issues/1238

**Comment by bertvannuffelen** [comment]
During WG 21 Oct 2021, the wg accepted to improve the definitions.
